version: "v1"
meta:
  description: "Ruleset for generating concrete search queries for Takprodam product search"
limits:
  max_queries_total: 14
  max_queries_per_bucket: 5
  min_queries_total: 8
  max_keywords_from_description: 4

age_segments:
  infant:
    age_min: 0
    age_max: 2
    base_queries:
      - "погремушка"
      - "прорезыватель"
      - "мягкая игрушка"
      - "развивающий коврик"
      - "мобил на кроватку"
      - "пеленка"
      - "комбинезон"
      - "детский плед"
      - "карусель на кроватку"
      - "ночник"
    vibes:
      cozy:
        queries:
          - "детский плед"
          - "ночник"
          - "мягкая игрушка"
          - "пижама"
          - "спальный мешок"
      practical:
        queries:
          - "подгузники"
          - "бутылочка"
          - "термосумка для бутылочек"
          - "слюнявчик"
          - "детская посуда"
      fun:
        queries:
          - "погремушка"
          - "прорезыватель"
          - "игрушка для ванной"
          - "пирамидка"
      wow:
        queries:
          - "карусель на кроватку"
          - "проектор звездного неба"
          - "интерактивная игрушка"
      creative:
        queries:
          - "сенсорные карточки"
          - "книга-игрушка"
      tech:
        queries:
          - "радионяня"
          - "видеоняня"
  preschool:
    age_min: 3
    age_max: 6
    base_queries:
      - "конструктор"
      - "кукла"
      - "машинка"
      - "пазлы"
      - "набор для творчества"
      - "раскраска"
      - "игровой набор"
      - "настольная игра"
      - "книга с наклейками"
      - "ночник"
    vibes:
      cozy:
        queries:
          - "детский плед"
          - "пижама"
          - "ночник"
          - "мягкая игрушка"
      practical:
        queries:
          - "рюкзак детский"
          - "термокружка"
          - "ланчбокс"
          - "детская посуда"
      fun:
        queries:
          - "мыльные пузыри"
          - "игрушка для ванной"
          - "машинка"
          - "кукла"
          - "набор для опытов"
      wow:
        queries:
          - "интерактивная игрушка"
          - "проектор звездного неба"
          - "тент домик"
      creative:
        queries:
          - "набор для лепки"
          - "раскраска"
          - "набор для рисования"
          - "мозаика"
      tech:
        queries:
          - "детский планшет"
          - "говорящая игрушка"
  child:
    age_min: 7
    age_max: 12
    base_queries:
      - "конструктор"
      - "настольная игра"
      - "набор для творчества"
      - "книга"
      - "пазлы"
      - "роликовые коньки"
      - "скейтборд"
      - "спортивный мяч"
      - "рюкзак"
      - "наушники"
    vibes:
      cozy:
        queries:
          - "плед"
          - "ночник"
          - "пижама"
          - "подушка"
      practical:
        queries:
          - "бутылка для воды"
          - "пенал"
          - "органайзер"
          - "настольная лампа"
      fun:
        queries:
          - "настольная игра"
          - "набор фокусов"
          - "конструктор"
          - "радиоуправляемая машинка"
          - "слайм набор"
      wow:
        queries:
          - "квадрокоптер"
          - "проектор звездного неба"
          - "гироскутер"
      creative:
        queries:
          - "набор для рисования"
          - "набор для выжигания"
          - "набор для вышивания"
          - "модель для сборки"
      tech:
        queries:
          - "смарт часы"
          - "наушники"
          - "портативная колонка"
  teen:
    age_min: 13
    age_max: 17
    base_queries:
      - "наушники"
      - "портативная колонка"
      - "смарт часы"
      - "рюкзак"
      - "термокружка"
      - "пауэрбанк"
      - "настольная лампа"
      - "настольная игра"
      - "скейтборд"
      - "уходовая косметика"
    vibes:
      cozy:
        queries:
          - "плед"
          - "аромасвеча"
          - "ночник"
          - "подушка"
      practical:
        queries:
          - "пауэрбанк"
          - "органайзер"
          - "бутылка для воды"
          - "клавиатура"
      fun:
        queries:
          - "настольная игра"
          - "карточная игра"
          - "гирлянда"
          - "постер"
      wow:
        queries:
          - "игровая мышь"
          - "led лента"
          - "проектор"
      creative:
        queries:
          - "скетчбук"
          - "набор для рисования"
          - "набор для маникюра"
      tech:
        queries:
          - "наушники"
          - "портативная колонка"
          - "смарт часы"
          - "пауэрбанк"
  young_adult:
    age_min: 18
    age_max: 29
    base_queries:
      - "наушники"
      - "портативная колонка"
      - "кофемолка"
      - "термокружка"
      - "пауэрбанк"
      - "сумка"
      - "аромасвеча"
      - "настольная игра"
      - "кухонный нож"
      - "спорт бутылка"
    vibes:
      cozy:
        queries:
          - "плед"
          - "аромасвеча"
          - "диффузор"
          - "ночник"
      practical:
        queries:
          - "кофемолка"
          - "электрочайник"
          - "набор посуды"
          - "органайзер"
          - "пауэрбанк"
      fun:
        queries:
          - "настольная игра"
          - "карточная игра"
          - "набор для коктейлей"
          - "фотобокс"
      wow:
        queries:
          - "проектор"
          - "умная колонка"
          - "электросамокат"
      creative:
        queries:
          - "скетчбук"
          - "набор для рисования"
          - "набор для свечеварения"
      tech:
        queries:
          - "умная колонка"
          - "наушники"
          - "пауэрбанк"
          - "смарт часы"
  adult:
    age_min: 30
    age_max: 49
    base_queries:
      - "кофемолка"
      - "кофеварка"
      - "электрочайник"
      - "набор ножей"
      - "аромасвеча"
      - "диффузор"
      - "плед"
      - "настольная лампа"
      - "термос"
      - "набор полотенец"
    vibes:
      cozy:
        queries:
          - "плед"
          - "аромасвеча"
          - "диффузор"
          - "подушка"
          - "ночник"
      practical:
        queries:
          - "кофемолка"
          - "кофеварка"
          - "электрочайник"
          - "набор ножей"
          - "органайзер"
      fun:
        queries:
          - "настольная игра"
          - "карточная игра"
          - "набор для гриля"
      wow:
        queries:
          - "робот пылесос"
          - "умная колонка"
          - "проектор"
      creative:
        queries:
          - "набор для рисования"
          - "набор для свечеварения"
          - "набор для выпечки"
      tech:
        queries:
          - "умная колонка"
          - "робот пылесос"
          - "смарт часы"
          - "наушники"
  mature:
    age_min: 50
    age_max: 120
    base_queries:
      - "чайник"
      - "термос"
      - "плед"
      - "набор полотенец"
      - "настольная лампа"
      - "часы настенные"
      - "массажер"
      - "ортопедическая подушка"
      - "сахарница"
      - "книга"
    vibes:
      cozy:
        queries:
          - "плед"
          - "ортопедическая подушка"
          - "аромасвеча"
          - "ночник"
      practical:
        queries:
          - "массажер"
          - "тонометр"
          - "термос"
          - "чайник"
          - "набор полотенец"
      fun:
        queries:
          - "настольная игра"
          - "пазлы"
          - "книга"
      wow:
        queries:
          - "массажер для ног"
          - "электрическое одеяло"
      creative:
        queries:
          - "набор для вышивания"
          - "алмазная мозаика"
      tech:
        queries:
          - "умная колонка"
          - "электронная книга"

gender_map:
  male:
    queries:
      - "ремень"
      - "кошелек мужской"
      - "портмоне"
      - "галстук"
      - "запонки"
      - "бритва"
      - "триммер"
      - "набор для бритья"
      - "мужской парфюм"
      - "термокружка"
      - "рюкзак"
      - "держатель для телефона"
  female:
    queries:
      - "косметичка"
      - "шкатулка для украшений"
      - "зеркало косметическое"
      - "набор косметики"
      - "крем для рук"
      - "маска для лица"
      - "аромасвеча"
      - "диффузор"
      - "шарф"
      - "сумка"
      - "набор для маникюра"
      - "украшение"
  unisex:
    queries:
      - "плед"
      - "аромасвеча"
      - "диффузор"
      - "термокружка"
      - "power bank"
      - "настольная игра"
      - "набор для чая"
      - "кофейный набор"
      - "ночник"
      - "органайзер"
      - "бутылка для воды"
      - "набор для ухода"

relationship_map:
  parent:
    queries:
      - "кофеварка"
      - "набор ножей"
      - "набор полотенец"
      - "аромасвеча"
      - "плед"
  partner:
    queries:
      - "аромасвеча"
      - "диффузор"
      - "набор для коктейлей"
      - "украшения"
      - "плед"
  friend:
    queries:
      - "настольная игра"
      - "портативная колонка"
      - "термокружка"
      - "скетчбук"
      - "аромасвеча"
  colleague:
    queries:
      - "ежедневник"
      - "ручка"
      - "термокружка"
      - "органайзер"
      - "настольная лампа"
  child:
    queries:
      - "конструктор"
      - "кукла"
      - "машинка"
      - "настольная игра"
      - "набор для творчества"
  other:
    queries:
      - "плед"
      - "аромасвеча"
      - "термокружка"
      - "настольная игра"
      - "книга"

occasion_map:
  birthday:
    queries:
      - "тортница"
      - "настольная игра"
      - "портативная колонка"
      - "аромасвеча"
      - "плед"
  new_year:
    queries:
      - "гирлянда"
      - "елочные игрушки"
      - "аромасвеча"
      - "плед"
      - "набор кружек"
  valentines:
    queries:
      - "аромасвеча"
      - "диффузор"
      - "набор для коктейлей"
      - "плед"
      - "фоторамка"
  march_8:
    queries:
      - "аромасвеча"
      - "диффузор"
      - "уходовая косметика"
      - "цветочное мыло"
      - "плед"
  just_because:
    queries:
      - "термокружка"
      - "аромасвеча"
      - "плед"
      - "настольная игра"
      - "книга"
  anniversary:
    queries:
      - "плед"
      - "набор посуды"
      - "фоторамка"
      - "аромасвеча"
      - "диффузор"
  graduation:
    queries:
      - "ручка"
      - "ежедневник"
      - "портативная колонка"
      - "пауэрбанк"
      - "рюкзак"
  housewarming:
    queries:
      - "набор ножей"
      - "набор полотенец"
      - "аромасвеча"
      - "плед"
      - "настольная лампа"

interests_map:
  coffee:
    queries:
      - "кофемолка"
      - "кофеварка"
      - "турка"
      - "френч пресс"
      - "кружка"
  tech:
    queries:
      - "наушники"
      - "пауэрбанк"
      - "умная колонка"
      - "смарт часы"
      - "проводная зарядка"
  sports:
    queries:
      - "спорт бутылка"
      - "коврик для йоги"
      - "фитнес резинки"
      - "гантели"
      - "скакалка"
  beauty:
    queries:
      - "уходовая косметика"
      - "набор для маникюра"
      - "фен"
      - "щипцы для волос"
      - "косметичка"
  cooking:
    queries:
      - "набор ножей"
      - "форма для выпечки"
      - "сковорода"
      - "кухонный нож"
      - "набор специй"
  home:
    queries:
      - "плед"
      - "аромасвеча"
      - "диффузор"
      - "настольная лампа"
      - "набор полотенец"
  books:
    queries:
      - "книга"
      - "электронная книга"
      - "закладка"
      - "лампа для чтения"
      - "подставка для книг"
  music:
    queries:
      - "наушники"
      - "портативная колонка"
      - "виниловый проигрыватель"
      - "микрофон"
      - "держатель для микрофона"
  travel:
    queries:
      - "дорожная подушка"
      - "органайзер для путешествий"
      - "чехол на чемодан"
      - "термокружка"
      - "набор дорожных флаконов"
  games:
    queries:
      - "настольная игра"
      - "карточная игра"
      - "игровая мышь"
      - "коврик для мыши"
      - "наушники"
  pets:
    queries:
      - "лежанка для кошки"
      - "когтеточка"
      - "миска для собаки"
      - "игрушка для кошки"
      - "игрушка для собаки"
  health:
    queries:
      - "тонометр"
      - "массажер"
      - "ортопедическая подушка"
      - "грелка"
      - "увлажнитель воздуха"
  kids:
    queries:
      - "конструктор"
      - "кукла"
      - "машинка"
      - "настольная игра"
      - "набор для творчества"

description_keywords_map:
  "кофе":
    queries:
      - "кофемолка"
      - "кофеварка"
      - "турка"
      - "френч пресс"
  "чай":
    queries:
      - "чайник"
      - "заварочный чайник"
      - "набор кружек"
  "уют":
    queries:
      - "плед"
      - "аромасвеча"
      - "диффузор"
      - "ночник"
  "фитнес":
    queries:
      - "коврик для йоги"
      - "фитнес резинки"
      - "гантели"
  "путеше":
    queries:
      - "дорожная подушка"
      - "органайзер для путешествий"
      - "чехол на чемодан"
  "геймер":
    queries:
      - "игровая мышь"
      - "коврик для мыши"
      - "наушники"
  "кошк":
    queries:
      - "лежанка для кошки"
      - "когтеточка"
      - "игрушка для кошки"
  "собак":
    queries:
      - "миска для собаки"
      - "игрушка для собаки"
      - "поводок"
  "музык":
    queries:
      - "наушники"
      - "портативная колонка"
      - "микрофон"

banned:
  banned_queries:
    - "подарок"
    - "для дома"
  negative_keywords:
    - "18+"
    - "эрот"
    - "казино"
    - "табак"
    - "вейп"
